export type ImageFileNames = { imageFileNames: string[] };
export type ParamFileNames = { paramFileNames: string[] };
export type FileNames = ImageFileNames & ParamFileNames;

export type LoraTrainingParams = {
  cache_latents?: boolean;
  caption_extension?: string;
  clip_skip?: number;
  color_aug?: boolean;
  enable_bucket?: boolean;
  epoch?: string;
  flip_aug?: boolean;
  full_fp16?: boolean;
  gradient_accumulation_steps?: number;
  gradient_checkpointing?: boolean;
  keep_tokens?: string;
  learning_rate?: string;
  logging_dir?: string;
  lora_network_weights?: string;
  lr_scheduler?: string;
  lr_scheduler_num_cycles?: string;
  lr_scheduler_power?: string;
  lr_warmup?: string;
  max_data_loader_n_workers?: string;
  max_resolution?: string;
  max_token_length?: string;
  max_train_epochs?: string;
  mem_eff_attn?: boolean;
  mixed_precision?: string;
  model_list?: string;
  network_alpha?: number;
  network_dim?: number;
  no_token_padding?: boolean;
  num_cpu_threads_per_process?: number;
  output_dir?: string;
  output_name?: string;
  pretrained_model_name_or_path?: string;
  prior_loss_weight?: number;
  reg_data_dir?: string;
  resume?: string;
  save_every_n_epochs?: string;
  save_model_as?: string;
  save_precision?: string;
  save_state?: boolean;
  seed?: string;
  shuffle_caption?: boolean;
  stop_text_encoder_training?: number;
  text_encoder_lr?: string;
  train_batch_size?: number;
  train_data_dir?: string;
  training_comment?: string;
  unet_lr?: string;
  use_8bit_adam?: boolean;
  v2?: boolean;
  v_parameterization?: boolean;
  xformers?: boolean;
};

export type Model = { hash: string; name: string };

export type NoEmit = { noEmit?: boolean };

export type Txt2ImgOverrides = {
  cfgScale?: number;
  clipSkip?: number;
  cutoffDisableForNeg?: boolean;
  cutoffEnabled?: true;
  cutoffInterpolation?: string;
  cutoffPadding?: string;
  cutoffStrong?: boolean;
  cutoffTargets?: string[];
  cutoffWeight?: number;
  denoisingStrength?: number;
  hiresScale?: number;
  model?: string;
  negTemplate?: string;
  restoreFaces?: boolean;
  sampler?: string;
  seed?: number;
  steps?: number;
  subseed?: number;
  subseedStrength?: number;
  upscaler?: string;
  template?: string;
  vae?: string;
};
